apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shopnow-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: <your-account>.dkr.ecr.<region>.amazonaws.com/<your-username>-shopnow/backend:latest
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: db-secret
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: shopnow-demo
spec:
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
